openapi: 3.0.1
servers:
  - url: https://ok.example
    description: production
  - url: http://ok.sandbox.examle
    x-sandbox: true
    description: ok

  - url: http://ko.example
    description: should be https
  - url: http://ok.sandbox.examle
    x-sandbox: false
    description: should be http