components:
  schemas:
    ko_Number:
      schema:
        type: number
    Number:
      schema:
        type: number
        format: int32
    ko_Integer:
      schema:
        type: integer
    Integer:
      schema:
        type: integer
        format: int32
openapi: 3.0.1
paths:
  /number-ok:
    put:
      requestBody:
       content:
         application/json-patch+json:
           schema:
             type: number
             format: int32
  /integer-ok:
    put:
      requestBody:
      content:
        application/json-patch+json:
          schema:
            $ref: '#/components/schemas/Integer'

  /number-ko:
     put:
      requestBody:
       content:
         application/json-patch+json:
           schema:
             type: number
  /integer-ko:
    put:
      requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ko_Integer'

