openapi: 3.0.1
paths:
  /ok-default-use-problem:
    get:
      responses:
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /ko-default-use-problem:
    get:
      responses:
        default:
          content:
            application/json: {}
  /ko-bad-schema-use-problem:
    get:
      responses:
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ko_Problem'
  /ko-response-not-object:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
  /ok-response-is-object:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  foo:
                    type: string
  /ko-response-is-string:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ko_String'

components:
  schemas:
    ko_String:
      type: string

    Problem:
      properties:
        title:
          type: string
        status:
          type: integer
          format: int32

    ko_Problem:
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32