openapi: 3.0.1
paths:
  /ok-default-use-problem:
    get:
      responses:
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+xml:
              schema:
                $ref: '#/components/schemas/Problem' 
  /ko-default-use-problem:
    get:
      responses:
        default:
          content:
            application/json: {}
  /ko-error-use-problem:
    get:
      responses:          
        "400":
          content:
            not/problem: {}

  /ko-bad-schema-use-problem:
    get:
      responses:
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ko_Problem'

components:
  schemas:
    Problem:
      properties:
        title:
          type: string
        status:
          type: integer
          format: int32

    ko_Problem:
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32